users= [('hr_zoom@tomofun.com', '5xFG6OOSTUCyrWixEAjxTQ', 'HR', 'Tomofun'),
    ('pm@tomofun.com', '6HUwNg6lQLuY4D6ZyOn2DQ', 'Rupa', 'Huang'), 
    ('cammy@tomofun.com', 'bX38VsxLTlG57Ml1xutHpQ', 'Cammy', 'Lin'), 
    ('it@tomofun.com', 'HD5LDJyBQj6DIUg3aNAWoA', 'Tomofun', 'IT'),
    ('hr@tomofun.com', 'hKJDp5SbRA-TCwDFP6b2tQ', 'Tomofun', 'HR'), 
    ('ai_comp2021@tomofun.com', 'JbxO25woR0mEgzU-LJrY7w', 'ai', 'comp2021'),
    ('claire@tomofun.com', 'kFBGwCKBSu-urVQKsJELrw', 'Claire', 'Cheng'),
    ('maggie@tomofun.com', 'nJGI12QNTWel1Np5xYr4aw', 'Maggie', 'Cheung'), 
    ('phoebe@tomofun.com', 'pi-EOLuWTzSaBMcjTS7YOw', 'Phoebe', 'Chu'), 
    ('eu_team@tomofun.com', 'po_eXA9cQaGfJ2lRf-YcYA', 'EU', 'Team'),
    ('zoe@tomofun.com', 'qg_CIqJFQCeJlnJILg41_A', 'Zoe', 'Lin'), 
    ('nobel@tomofun.com', 'rixyQ-EQQv6rkHfCqGnrSg', 'Nobel', 'Hsu'), 
    ('careers.ph@tomofun.com', 'rjI9fjHqTO2M75oU2SCppg', 'Tomofun PH', 'Recruitment'), 
    ('jp_team@tomofun.com', 'tU7KTf9dQ1KNz6OsUnghOw', 'JP', 'Team'),
    ('bonniechieh@gmail.com', 'u9czDcxMSPq-yzoTiS9WUQ', 'Bonnie', 'Chien'),
    ('support@tomofun.com', 'wjM6FD29TSe1mKV3fGSjkg', 'Support', 'Tomofun'),
    ('tina@tomofun.com', 'wxIKWmLGQHC1xfC2R8Jw0g', 'Yi An', 'Chang'), 
    ('pai@tomofun.com', 'xVVy1TgNRImyNZwM-sZCTg', 'Pai', 'Hsueh'), 
    ('connie@tomofun.com', 'YAXjy6tFSfWUZUEIhE3pOw', 'Connie', 'Tseng'),
    ('it_nYr2_a6UQf-KgXOgEJC_xg@tomofun.com','nYr2_a6UQf-KgXOgEJC_xg', 'Learn', 'Room'),
    ('it_xIV7r-ZBQjKwntnAb-Xw-Q@tomofun.com', 'xIV7r-ZBQjKwntnAb-Xw-Q', 'Explore', 'Room'),
    ('rooms_Gm-YB4KkSgmQlewn45SHGA@tomofun.com', 'Gm-YB4KkSgmQlewn45SHGA', 'Open','Minded'),
    ('rooms_O9M7TuCWSGCDyP3XMbAnyg@tomofun.com','O9M7TuCWSGCDyP3XMbAnyg','Room', 'Build'),
    ('rooms_OoF6Kl4dR3uflZJcsc8zsg@tomofun.com', 'OoF6Kl4dR3uflZJcsc8zsg','Customer', 'Love'),
    ('rooms_v_f516YwS2e0mV02o-a6mg@tomofun.com', 'v_f516YwS2e0mV02o-a6mg', 'Room', 'Measure'),
    ('rooms_y30wKjFgT-2CK9yKl3TGTw@tomofun.com', 'y30wKjFgT-2CK9yKl3TGTw', 'Room', 'Agile'),
    ('rooms_ZU986YdwTBmCMUOSNvmgpQ@tomofun.com', 'ZU986YdwTBmCMUOSNvmgpQ', 'Room', 'Fun')]
